DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS central_offices CASCADE;
DROP TABLE IF EXISTS cities CASCADE;